version: "3.7"

services:

  redis:
    image: redis:alpine
    container_name: my-container
    build:
      context: ./dir
      dockerfile: Dockerfile-alternate
      args:
        buildno: 1
    ports:
      - "6379"
    networks:
      - frontend
    volumes:
      - "/tmp:/data/tmp"
      - db-data:/var/lib
    depends_on:
      - otro-servicio

networks:
  frontend:

volumes:
  db-data: